### ISSUE TITLE
Doesn't work 

### ISSUE THREAD

**Issue by yamyoume** [vitorgalvao/alfred-workflows#103]
#### Setup info

* Workflow name: DownMedia
* Workflow version: 2020.1
* Alfred version: 4
* macOS version: 10.15.2

#### Description of issue

doesn't work

#### Debugger output

```
[23:47:19.781] Logging Started...
[23:47:22.120] DownMedia[Script Filter] Queuing argument ''
[23:47:22.346] DownMedia[Script Filter] Script with argv '' finished
[23:47:22.347] ERROR: DownMedia[Script Filter] Code 1: /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/open3.rb:213:in `spawn': No such file or directory - /Users/yamantarakji/Library/Application (Errno::ENOENT)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/open3.rb:213:in `popen_run'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/open3.rb:159:in `popen2'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/open3.rb:342:in `capture2'
	from /Users/yamantarakji/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.CEE867B6-C356-4C11-8836-3CB8D8A6C4B3/downmedia_functions.rb:216:in `get_title_url'
	from /Users/yamantarakji/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.CEE867B6-C356-4C11-8836-3CB8D8A6C4B3/downmedia_functions.rb:20:in `show_options'
	from /Users/yamantarakji/Library/Caches/com.runningwithcrayons.Alfred/Workflow Scripts/950845A9-E407-4681-AD75-8460165FDA94:3:in `<main>'
```

**Comment by yamyoume** [comment]
Sorry I downloaded version from here and now it works ! thanks for the great work

**Comment by karnilaev** [comment]
I have the same issue: 

* Workflow name: DownMedia
* Workflow version: 20.3
* Alfred version: 4.0.9[1144]
* macOS version: 10.15.5 (19F101)

debugger:

```[14:33:07.627] DownMedia[Script Filter] Queuing argument ''
[14:33:08.044] DownMedia[Script Filter] Script with argv '' finished
[14:33:08.052] ERROR: DownMedia[Script Filter] Code 1: Could not download resource.
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/open3.rb:213:in `spawn': No such file or directory - pbpaste (Errno::ENOENT)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/open3.rb:213:in `popen_run'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/open3.rb:159:in `popen2'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/open3.rb:342:in `capture2'
	from /Users/yuri/Dropbox/service/Alfred.alfredpreferences/workflows/user.workflow.180782E5-EDA7-4CCC-83D8-6D06807BC8CD/downmedia_functions.rb:19:in `show_options'
	from /Users/yuri/Library/Caches/com.runningwithcrayons.Alfred/Workflow Scripts/46BCAC60-03C5-4618-A9F4-5558A150E9C6:3:in `<main>'```

**Comment by vitorgalvao** [comment]
https://www.alfredforum.com/topic/2045-downmedia-%E2%80%94-download-media-from-popular-sources/page/13/?tab=comments#comment-73802
