### ISSUE TITLE
Error loading bookmarks

### ISSUE THREAD

**Issue by Nerian** [vitorgalvao/alfred-workflows#109]
Hi,

#### Setup info

* Workflow name: PinPlus 
* Workflow version: 20.8
* Alfred version: 4.0.9
* macOS version: 10.15.5

#### Description of issue

When I try to search for bookmarks I get no result This has been happening for at least the last  3 days. I tried removing and reinstalling PinPlus but the same error.

#### Debugger output

```
[09:54:24.822] Logging Started...
[09:54:26.984] PinPlus[Hotkey] Processing complete
[09:54:26.988] PinPlus[Hotkey] Passing output '' to Script Filter
[09:54:27.014] PinPlus[Script Filter] Queuing argument '(null)'
[09:54:28.200] PinPlus[Script Filter] Script with argv '(null)' finished
[09:54:28.203] ERROR: PinPlus[Script Filter] Code 1: /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/json/common.rb:156:in `parse': 767: unexpected token at '﻿{"update_time":"2020-05-26T14:31:42Z"} (JSON::ParserError)
	
'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/json/common.rb:156:in `parse'
	from /Users/Nerian/Dropbox/Backup/Alfred.alfredpreferences/workflows/user.workflow.BF3D4171-9A18-48DE-9DD4-3715F3F88589/pinplus.rb:104:in `synced_with_website?'
	from /Users/Nerian/Dropbox/Backup/Alfred.alfredpreferences/workflows/user.workflow.BF3D4171-9A18-48DE-9DD4-3715F3F88589/pinplus.rb:154:in `fetch_bookmarks'
	from /Users/Nerian/Dropbox/Backup/Alfred.alfredpreferences/workflows/user.workflow.BF3D4171-9A18-48DE-9DD4-3715F3F88589/pinplus.rb:147:in `show_bookmarks'
	from /Users/Nerian/Library/Caches/com.runningwithcrayons.Alfred/Workflow Scripts/96602DA4-920A-4617-9753-839C8A77610F:3:in `<main>'
```

**Comment by vitorgalvao** [comment]
Try deleting the cache directory: `/Users/Nerian/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/com.vitorgalvao.alfred.pinplus`

**Comment by Nerian** [comment]
Hi,

I tried doing that but same error.

I did some debugging and it appears that the code is failing to parse the json response.

In this line: https://github.com/vitorgalvao/alfred-workflows/blob/master/PinPlus/source/pinplus.rb#L103

```
JSON.parse(URI("https://api.pinboard.in/v1/posts/update?auth_token=#{grab_pinboard_token}&format=json").read)['update_time']
JSON::ParserError: 751: unexpected token at '{"update_time":"2020-05-26T14:31:42Z"}

'
	from /Users/Nerian/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/json/common.rb:156:in `parse'
	from /Users/Nerian/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/json/common.rb:156:in `parse'
	from (irb):36
	from /Users/Nerian/.rvm/rubies/ruby-2.4.2/bin/irb:11:in `<main>'
```

```
2.4.2 :014 >   puts URI("https://api.pinboard.in/v1/posts/update?auth_token=#{grab_pinboard_token}&format=json").read
{"update_time":"2020-05-26T14:31:42Z"}

 => nil
```

```
2.4.2 :015 > URI("https://api.pinboard.in/v1/posts/update?auth_token=#{grab_pinboard_token}&format=json").read
 => "{\"update_time\":\"2020-05-26T14:31:42Z\"}\n\t\n"
```

**Comment by vitorgalvao** [comment]
Something’s going on. I haven’t touched that code in a while, it seems to be something in the API response. [I’ve asked](https://twitter.com/vhgalvao/status/1272621821276323840).

**Comment by vitorgalvao** [comment]
Found the problem, [already emailed Maciej](https://twitter.com/vhgalvao/status/1272633594700353543). Fix needs to be done upstream, at which point the Workflow should start working again.

**Comment by Nerian** [comment]
Excellent, thanks!

**Comment by vitorgalvao** [comment]
https://www.alfredforum.com/topic/10538-pinplus-%E2%80%94-interact-with-your-pinboard-bookmarks/page/4/?tab=comments#comment-77348
