### ISSUE TITLE
shortfilms doesn't work anymore

### ISSUE THREAD

**Issue by gbstan** [vitorgalvao/alfred-workflows#110]
#### Setup info

* Workflow name: ShortFilms
* Workflow version: 20.5
* Alfred version: 4.0.9[1144]
* macOS version: 10.15.5

#### Description of issue

shorts doesn't return anything any more.

#### Debugger output

```
[13:58:34.178] ShortFilms[Script Filter] Queuing argument '(null)'
[13:58:34.974] ShortFilms[Script Filter] Script with argv '(null)' finished
[13:58:34.977] ERROR: ShortFilms[Script Filter] Code 1: /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/net/protocol.rb:44:in `connect_nonblock': SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (certificate has expired) (OpenSSL::SSL::SSLError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/net/protocol.rb:44:in `ssl_socket_connect'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/net/http.rb:996:in `connect'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/net/http.rb:930:in `do_start'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/net/http.rb:919:in `start'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/open-uri.rb:337:in `open_http'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/open-uri.rb:756:in `buffer_open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/open-uri.rb:226:in `block in open_loop'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/open-uri.rb:224:in `catch'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/open-uri.rb:224:in `open_loop'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/open-uri.rb:165:in `open_uri'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/open-uri.rb:736:in `open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/open-uri.rb:744:in `read'
	from /Users/guy-bartstan/Desktop/Dropbox/Alfred_Sync_Folder/Alfred.alfredpreferences/workflows/user.workflow.F162358A-BD4F-4675-9678-1297FB45F96F/shortfilms:16:in `<main>'
```

**Comment by vitorgalvao** [comment]
Please update and try again. Should be fixed with a workaround. The error is due to a bunch of certificates having expired recently.
