### ISSUE TITLE
DownMedia can't download youtubedl

### ISSUE THREAD

**Issue by pythoninja** [vitorgalvao/alfred-workflows#113]
Hi, I have an issue with fresh DownMedia workflow, you can see details below.

#### Setup info

* Workflow name: DownMedia
* Workflow version: v20.7
* Alfred version: 4.0.9
* macOS version: Catalina (10.15.5 (19F101))

#### Description of issue

I am using Alfred backup dir on my synced Dropbox folder (if it's the case)

1. Download and install extension
2. Run `dv`

Please check debug info.

#### Debugger output

```
[09:50:07.274] DownMedia[Script Filter] Queuing argument ''
[09:50:07.730] DownMedia[Script Filter] Script with argv '' finished
[09:50:07.736] ERROR: DownMedia[Script Filter] Code 1: Could not download youtubedl.
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/open3.rb:213:in `spawn': No such file or directory - pbpaste (Errno::ENOENT)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/open3.rb:213:in `popen_run'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/open3.rb:159:in `popen2'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/open3.rb:342:in `capture2'
	from /Users/psv/Dropbox/Backup/[Macos] Alfredapp/Alfred.alfredpreferences/workflows/user.workflow.61DA1006-029C-484E-B128-1C48A0872AEB/downmedia_functions.rb:38:in `show_options'
	from /Users/psv/Library/Caches/com.runningwithcrayons.Alfred/Workflow Scripts/B16A54D2-FBC2-4F93-8BF2-8DD5BFAF36F2:3:in `<main>'
```

**Comment by pythoninja** [comment]
I had fixed it with `brew install youtube-dl`
