### ISSUE TITLE
DownMedia - `pbpaste` error

### ISSUE THREAD

**Issue by chenasraf** [vitorgalvao/alfred-workflows#114]
https://github.com/vitorgalvao/alfred-workflows/blob/9b424e4ed0a7c3381daff3ed4224ff97b221725a/DownMedia/source/downmedia_functions.rb#L38

The `pbpaste` command isn't available to ruby for some reason, through it's PATH alias (at least on my machine).
I changed the script to use `/usr/bin/pbpaste` instead, and it worked for me:

```
 clipboard = Open3.capture2('/usr/bin/pbpaste').first.strip 
```
 Perhaps doing something more fool-proof is a better idea.

This is the original error in the workflow:

```
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/open3.rb:213:in `spawn': No such file or directory - pbpaste (Errno::ENOENT)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/open3.rb:213:in `popen_run'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/open3.rb:159:in `popen2'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/open3.rb:342:in `capture2'
	from /Users/USER/Google Drive/Sync/Alfred.alfredpreferences/workflows/user.workflow.C5AEB507-72D1-48C1-8302-E816CE76C455/downmedia_functions.rb:38:in `show_options'
	from /Users/USER/Library/Caches/com.runningwithcrayons.Alfred/Workflow Scripts/41A117AD-8F4B-44C9-B99D-25105358E0AE:3:in `<main>'
```

**Comment by chenasraf** [comment]
My apologies for the format, and thank you for the response.
