### ISSUE TITLE
Started getting an error with MarkdownTransform

### ISSUE THREAD

**Issue by nikitavoloboev** [vitorgalvao/alfred-workflows#50]
I tried to convert some markdown on Alfred Forum to BBCode and it did nothing. This is what I get in the log:

```Bash
Starting debug for 'MarkdownTransform'

[2017-12-19 18:03:17][ERROR: action.script] /Users/nikivi/alfred/Alfred.alfredpreferences/workflows/user.workflow.A4C9B6F5-B1B9-4B49-AC24-C13F11C295C0/_licensed/Redcarpet/gems/redcarpet-3.4.0/lib/redcarpet.bundle: [BUG] Segmentation fault
ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]

-- Crash Report log information --------------------------------------------
   See Crash Report log file under the one of following:
     * ~/Library/Logs/CrashReporter
     * /Library/Logs/CrashReporter
     * ~/Library/Logs/DiagnosticReports
     * /Library/Logs/DiagnosticReports
   the more detail of.

-- Control frame information -----------------------------------------------
c:0008 p:-17577847621342 s:0040 e:000039 TOP    [FINISH]
c:0007 p:---- s:0038 e:000037 CFUNC  :require
c:0006 p:0113 s:0034 e:000033 METHOD /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55
c:0005 p:0007 s:0023 e:000022 TOP    /Users/nikivi/alfred/Alfred.alfredpreferences/workflows/user.workflow.A4C9B6F5-B1B9-4B49-AC24-C13F11C295C0/_licensed/Redcarpet/ [FINISH]
c:0004 p:---- s:0021 e:000020 CFUNC  :require
c:0003 p:0113 s:0017 e:000016 METHOD /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55
c:0002 p:0022 s:0006 E:000d08 EVAL   ./bbcode:4 [FINISH]
c:0001 p:0000 s:0002 E:001fd8 TOP    [FINISH]

./bbcode:4:in `<main>'
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Users/nikivi/alfred/Alfred.alfredpreferences/workflows/user.workflow.A4C9B6F5-B1B9-4B49-AC24-C13F11C295C0/_licensed/Redcarpet/gems/redcarpet-3.4.0/lib/redcarpet.rb:1:in `<top (required)>'
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'

-- C level backtrace information -------------------------------------------

-- Other runtime information -----------------------------------------------

* Loaded script: ./bbcode

* Loaded features:

    0 enumerator.so
    1 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin15/enc/encdb.bundle
    2 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin15/enc/trans/transdb.bundle
    3 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin15/rbconfig.rb
    4 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/thread.rb
    5 /Library/Ruby/Site/2.0.0/rubygems/compatibility.rb
    6 /Library/Ruby/Site/2.0.0/rubygems/defaults.rb
    7 /Library/Ruby/Site/2.0.0/rubygems/deprecate.rb
    8 /Library/Ruby/Site/2.0.0/rubygems/errors.rb
    9 /Library/Ruby/Site/2.0.0/rubygems/version.rb
   10 /Library/Ruby/Site/2.0.0/rubygems/requirement.rb
   11 /Library/Ruby/Site/2.0.0/rubygems/platform.rb
   12 /Library/Ruby/Site/2.0.0/rubygems/basic_specification.rb
   13 /Library/Ruby/Site/2.0.0/rubygems/stub_specification.rb
   14 /Library/Ruby/Site/2.0.0/rubygems/util/list.rb
   15 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin15/stringio.bundle
   16 /Library/Ruby/Site/2.0.0/rubygems/specification.rb
   17 /Library/Ruby/Site/2.0.0/rubygems/exceptions.rb
   18 /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_gem.rb
   19 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/monitor.rb
   20 /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb
   21 /Library/Ruby/Site/2.0.0/rubygems.rb

[NOTE]
You may have encountered a bug in the Ruby interpreter or extension libraries.
Bug reports are welcome.
Don't forget to include the above Crash Report log file.
For details: http://www.ruby-lang.org/bugreport.html

/Users/nikivi/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Scripts/032AD3C1-24AB-483F-9556-13EB40C6FAAF: line 3: 66497 Abort trap: 6           ./bbcode "${1}"
```

Thank you for any help.

**Comment by vitorgalvao** [comment]
It’s due to your ruby version. See the Workflow’s README.

**Comment by nikitavoloboev** [comment]
I ran `brew upgrade ruby` and ran the workflow again. I got this error now: 

```Bash
Starting debug for 'MarkdownTransform'

[2017-12-19 18:56:00][ERROR: action.script] /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': dlopen(/Users/nikivi/alfred/Alfred.alfredpreferences/workflows/user.workflow.A4C9B6F5-B1B9-4B49-AC24-C13F11C295C0/_licensed/Redcarpet/gems/redcarpet-3.4.0/lib/redcarpet.bundle, 9): Library not loaded: /usr/local/opt/ruby/lib/libruby.2.4.2.dylib (LoadError)
  Referenced from: /Users/nikivi/alfred/Alfred.alfredpreferences/workflows/user.workflow.A4C9B6F5-B1B9-4B49-AC24-C13F11C295C0/_licensed/Redcarpet/gems/redcarpet-3.4.0/lib/redcarpet.bundle
  Reason: image not found - /Users/nikivi/alfred/Alfred.alfredpreferences/workflows/user.workflow.A4C9B6F5-B1B9-4B49-AC24-C13F11C295C0/_licensed/Redcarpet/gems/redcarpet-3.4.0/lib/redcarpet.bundle
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/nikivi/alfred/Alfred.alfredpreferences/workflows/user.workflow.A4C9B6F5-B1B9-4B49-AC24-C13F11C295C0/_licensed/Redcarpet/gems/redcarpet-3.4.0/lib/redcarpet.rb:1:in `<top (required)>'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from ./bbcode:4:in `<main>'
```

**Comment by vitorgalvao** [comment]
Try the version just released.

**Comment by nikitavoloboev** [comment]
I get this: 
```Bash
❯ brew upgrade ruby
Updating Homebrew...
Error: ruby 2.4.3_1 already installed
```

**Comment by vitorgalvao** [comment]
The just released version of the Worlfow, not ruby.

**Comment by nikitavoloboev** [comment]
Still nothing happens. Get this in the debug log:
```Bash
Starting debug for 'MarkdownTransform'

[2017-12-19 19:03:31][ERROR: action.script] /Users/nikivi/alfred/Alfred.alfredpreferences/workflows/user.workflow.A4C9B6F5-B1B9-4B49-AC24-C13F11C295C0/_licensed/Redcarpet/gems/redcarpet-3.4.0/lib/redcarpet.bundle: [BUG] Segmentation fault
ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]

-- Crash Report log information --------------------------------------------
   See Crash Report log file under the one of following:
     * ~/Library/Logs/CrashReporter
     * /Library/Logs/CrashReporter
     * ~/Library/Logs/DiagnosticReports
     * /Library/Logs/DiagnosticReports
   the more detail of.

-- Control frame information -----------------------------------------------
c:0008 p:-17527712969150 s:0040 e:000039 TOP    [FINISH]
c:0007 p:---- s:0038 e:000037 CFUNC  :require
c:0006 p:0113 s:0034 e:000033 METHOD /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55
c:0005 p:0007 s:0023 e:000022 TOP    /Users/nikivi/alfred/Alfred.alfredpreferences/workflows/user.workflow.A4C9B6F5-B1B9-4B49-AC24-C13F11C295C0/_licensed/Redcarpet/ [FINISH]
c:0004 p:---- s:0021 e:000020 CFUNC  :require
c:0003 p:0113 s:0017 e:000016 METHOD /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55
c:0002 p:0022 s:0006 E:001078 EVAL   ./bbcode:4 [FINISH]
c:0001 p:0000 s:0002 E:002038 TOP    [FINISH]

./bbcode:4:in `<main>'
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Users/nikivi/alfred/Alfred.alfredpreferences/workflows/user.workflow.A4C9B6F5-B1B9-4B49-AC24-C13F11C295C0/_licensed/Redcarpet/gems/redcarpet-3.4.0/lib/redcarpet.rb:1:in `<top (required)>'
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'

-- C level backtrace information -------------------------------------------

-- Other runtime information -----------------------------------------------

* Loaded script: ./bbcode

* Loaded features:

    0 enumerator.so
    1 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin15/enc/encdb.bundle
    2 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin15/enc/trans/transdb.bundle
    3 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin15/rbconfig.rb
    4 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/thread.rb
    5 /Library/Ruby/Site/2.0.0/rubygems/compatibility.rb
    6 /Library/Ruby/Site/2.0.0/rubygems/defaults.rb
    7 /Library/Ruby/Site/2.0.0/rubygems/deprecate.rb
    8 /Library/Ruby/Site/2.0.0/rubygems/errors.rb
    9 /Library/Ruby/Site/2.0.0/rubygems/version.rb
   10 /Library/Ruby/Site/2.0.0/rubygems/requirement.rb
   11 /Library/Ruby/Site/2.0.0/rubygems/platform.rb
   12 /Library/Ruby/Site/2.0.0/rubygems/basic_specification.rb
   13 /Library/Ruby/Site/2.0.0/rubygems/stub_specification.rb
   14 /Library/Ruby/Site/2.0.0/rubygems/util/list.rb
   15 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin15/stringio.bundle
   16 /Library/Ruby/Site/2.0.0/rubygems/specification.rb
   17 /Library/Ruby/Site/2.0.0/rubygems/exceptions.rb
   18 /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_gem.rb
   19 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/monitor.rb
   20 /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb
   21 /Library/Ruby/Site/2.0.0/rubygems.rb

[NOTE]
You may have encountered a bug in the Ruby interpreter or extension libraries.
Bug reports are welcome.
Don't forget to include the above Crash Report log file.
For details: http://www.ruby-lang.org/bugreport.html

/Users/nikivi/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Scripts/927E6E57-E23F-497B-A94F-CDB69DF75EB3: line 3: 79395 Abort trap: 6           ./bbcode "${1}"
```

**Comment by vitorgalvao** [comment]
Redownload the latest version and try again.

**Comment by nikitavoloboev** [comment]
Thank you @vitorgalvao 

This worked.
