### ISSUE TITLE
MarkdownTransform failing to convert Markdown to HTML

### ISSUE THREAD

**Issue by volt4ire** [vitorgalvao/alfred-workflows#58]
When I trigger the shortcut I set to have MarkdowTransofrm convert markdown to HTML, I get the markdown in my keyboard, not the HTML. Can you please help me get the transformation to HTML to work? Thanks!

* Workflow name: MarkdownTransform
* Workflow version: 1.22.1
* Alfred version: 3.6.1
* macOS version: 10.13.4
* Command that failed: Convert Markdown to HTML
* Debugger output:

```
Starting debug for 'MarkdownTransform'

[2018-04-28 15:04:12][ERROR: action.script] /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': dlopen(/Users/rwbarat/Dropbox/Alfred.alfredpreferences/workflows/user.workflow.F7AF8794-3C7A-4FF8-B9B0-D716429C7446/_licensed/Redcarpet/gems/redcarpet-3.4.0/lib/redcarpet.bundle, 0x0009): required dylib '/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/libruby.2.0.0.dylib' not found, needed by '/Users/rwbarat/Dropbox/Alfred.alfredpreferences/workflows/user.workflow.F7AF8794-3C7A-4FF8-B9B0-D716429C7446/_licensed/Redcarpet/gems/redcarpet-3.4.0/lib/redcarpet.bundle'.  Did try: file not found '/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/libruby.2.0.0.dylib', file not found '/usr/lib/libruby.2.0.0.dylib', file not found '/usr/local/lib/libruby.2.0.0.dylib' - /Users/rwbarat/Dropbox/Alfred.alfredpreferences/workflows/user.workflow.F7AF8794-3C7A-4FF8-B9B0-D716429C7446/_licensed/Redcarpet/gems/redcarpet-3.4.0/lib/redcarpet.bundle (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/rwbarat/Dropbox/Alfred.alfredpreferences/workflows/user.workflow.F7AF8794-3C7A-4FF8-B9B0-D716429C7446/_licensed/Redcarpet/gems/redcarpet-3.4.0/lib/redcarpet.rb:1:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from ./html:4:in `<main>'
```

**Comment by vitorgalvao** [comment]
Try the latest version. It won’t convert the text on the first run, but it’ll run the fix so it works on the second run.
