### ISSUE TITLE
ShortFilms doesn't seem to work any more

### ISSUE THREAD

**Issue by gbstan** [vitorgalvao/alfred-workflows#99]
#### Setup info

* Workflow name: ShortFilms
* Workflow version: 1.13.12
* Alfred version: 4.0.7
* macOS version: 10.15.2 (Catalina)

#### Description of issue

Calling `shorts` doesn't produce a list of short films.

#### Debugger output

```
[20:28:49.465] ShortFilms[Script Filter] Queuing argument '(null)'
[20:29:01.484] ShortFilms[Script Filter] Script with argv '(null)' finished
[20:29:01.497] ERROR: ShortFilms[Script Filter] Code 1: /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/uri/rfc3986_parser.rb:21:in `split': URI must be ascii only "https://static.shortoftheweek.com/wp-content/uploads/2019/12/LITTLE-HANDS_STILL-1\u00A9Kinan_Massarani.jpg" (URI::InvalidURIError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/uri/rfc3986_parser.rb:73:in `parse'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/uri/common.rb:234:in `parse'
	from /Users/guy-bartstan/Desktop/Dropbox/Alfred_Sync_Folder/Alfred.alfredpreferences/workflows/user.workflow.F162358A-BD4F-4675-9678-1297FB45F96F/shortfilms:36:in `block in <main>'
	from /Users/guy-bartstan/Desktop/Dropbox/Alfred_Sync_Folder/Alfred.alfredpreferences/workflows/user.workflow.F162358A-BD4F-4675-9678-1297FB45F96F/shortfilms:21:in `each'
	from /Users/guy-bartstan/Desktop/Dropbox/Alfred_Sync_Folder/Alfred.alfredpreferences/workflows/user.workflow.F162358A-BD4F-4675-9678-1297FB45F96F/shortfilms:21:in `<main>'
```

**Comment by vitorgalvao** [comment]
That’s due to one specific video online now. It would fix itself in a few days.

But if you download the newest version of the Workflow, it will work.
